2020-08-06 12:21:48,757 - sLogger - INFO - DbConnection[connect]: Se inicia la coneccion a la Base de Datos
2020-08-06 12:21:48,758 - sLogger - INFO - DbConnection[connect]: DbServer: 0.tcp.ngrok.io:17747
2020-08-06 12:21:48,758 - sLogger - INFO - DbConnection[connect]: DbDataDase: FHC_DataBase
2020-08-06 12:21:48,758 - sLogger - INFO - DbConnection[connect]: DbUser: RaspiRoot
2020-08-06 12:21:48,797 - sLogger - ERROR - DbConnection[connect]: Ha surgido un error al conectarse a la Base de Datos
2020-08-06 12:21:48,798 - sLogger - ERROR - DbConnection[connect]: Error: ("No module named '_mysql'",)
2020-08-06 12:23:52,253 - sLogger - INFO - DbConnection[connect]: Se inicia la coneccion a la Base de Datos
2020-08-06 12:23:52,253 - sLogger - INFO - DbConnection[connect]: DbServer: 0.tcp.ngrok.io:17747
2020-08-06 12:23:52,254 - sLogger - INFO - DbConnection[connect]: DbDataDase: FHC_DataBase
2020-08-06 12:23:52,254 - sLogger - INFO - DbConnection[connect]: DbUser: RaspiRoot
2020-08-06 12:23:54,914 - sLogger - ERROR - DbConnection[connect]: Ha surgido un error al conectarse a la Base de Datos
2020-08-06 12:23:54,914 - sLogger - ERROR - DbConnection[connect]: Error: ("module 'sqlalchemy' has no attribute 'getEngine'",)
2020-08-06 12:24:48,699 - sLogger - INFO - DbConnection[connect]: Se inicia la coneccion a la Base de Datos
2020-08-06 12:24:48,699 - sLogger - INFO - DbConnection[connect]: DbServer: 0.tcp.ngrok.io:17747
2020-08-06 12:24:48,700 - sLogger - INFO - DbConnection[connect]: DbDataDase: FHC_DataBase
2020-08-06 12:24:48,700 - sLogger - INFO - DbConnection[connect]: DbUser: RaspiRoot
2020-08-06 12:24:51,430 - sLogger - INFO - DbConnection[connect]: Coneccion Exitosa!!!
